# Generated by Django 5.0.6 on 2024-07-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gouvernorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('gouvernorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.gouvernorat')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_abonnement', models.CharField(choices=[('ADSL', 'ADSL'), ('VDSL', 'VDSL'), ('Fibre optique', 'Fibre optique')], max_length=100)),
                ('localite', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=20)),
                ('civilite', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Mlle', 'Mlle')], max_length=4)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('type_piece_identite', models.CharField(choices=[('CIN', 'CIN'), ('Passport', 'Passport')], max_length=20)),
                ('numero_piece_identite', models.CharField(max_length=50)),
                ('telephone_contact', models.CharField(max_length=20)),
                ('gsm_contact', models.CharField(max_length=20)),
                ('gsm_contact_2', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_installation', models.TextField()),
                ('coordonnees', models.CharField(max_length=255)),
                ('cin_recto', models.FileField(upload_to='documents/')),
                ('cin_verso', models.FileField(upload_to='documents/')),
                ('contrat_tt', models.FileField(upload_to='documents/')),
                ('contrat_topnet', models.FileField(upload_to='documents/')),
                ('contrat_general_vente', models.FileField(upload_to='documents/')),
                ('frequence_paiement', models.CharField(choices=[('1', '1 mois'), ('3', '3 mois'), ('6', '6 mois'), ('12', '12 mois')], max_length=2)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.delegation')),
                ('gouvernorat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.gouvernorat')),
            ],
        ),
    ]
