# Generated by Django 5.0.6 on 2024-07-09 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('delegation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.delegation')),
            ],
        ),
        migrations.AlterField(
            model_name='contract',
            name='localite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contract.localite'),
        ),
    ]
