# Generated by Django 5.0.6 on 2024-07-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_localite_alter_contract_localite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='code_postal',
        ),
    ]
