# Generated by Django 5.0.6 on 2024-07-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_delegation_code_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cin_recto',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cin_verso',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contrat_general_vente',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contrat_topnet',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contrat_tt',
            field=models.FileField(max_length=255, upload_to=''),
        ),
    ]
