# Generated by Django 5.0.6 on 2024-07-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_cin_recto_alter_contract_cin_verso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='cin_recto',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cin_verso',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contrat_general_vente',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contrat_topnet',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contrat_tt',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
