# Generated by Django 5.0.6 on 2024-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_localite_code_postal_localite_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='type_smart_rapido',
            field=models.CharField(blank=True, choices=[('SMART Rapido 20M GU TOPNET', 'SMART Rapido 20M GU TOPNET'), ('SMART Rapido 30M GU TOPNET', 'SMART Rapido 30M GU TOPNET'), ('SMART Rapido 50M GU TOPNET', 'SMART Rapido 50M GU TOPNET'), ('SMART Rapido 100M GU TOPNET', 'SMART Rapido 100M GU TOPNET'), ('SMART RAPIDO 20M (sans voix)', 'SMART RAPIDO 20M (sans voix)'), ('SMART RAPIDO 30M (sans voix)', 'SMART RAPIDO 30M (sans voix)'), ('SMART RAPIDO 50M (sans voix)', 'SMART RAPIDO 50M (sans voix)'), ('SMART RAPIDO 100M (sans voix)', 'SMART RAPIDO 100M (sans voix)'), ('PROMO SMART RAPIDO 20M (Sans Voix)', 'PROMO SMART RAPIDO 20M (Sans Voix)'), ('PROMO SMART RAPIDO 30M (Sans Voix)', 'PROMO SMART RAPIDO 30M (Sans Voix)'), ('PROMO SMART RAPIDO 50M (Sans Voix)', 'PROMO SMART RAPIDO 50M (Sans Voix)'), ('PROMO SMART RAPIDO 100M (Sans Voix)', 'PROMO SMART RAPIDO 100M (Sans Voix)'), ('Fidélité SMART RAPIDO 50M (sans voix)', 'Fidélité SMART RAPIDO 50M (sans voix)')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type_abonnement',
            field=models.CharField(choices=[('ADSL', 'ADSL'), ('VDSL', 'VDSL'), ('Smart Fibre ', ' Smart Fibre '), ('SMART RAPIDO', 'SMART RAPIDO')], max_length=100),
        ),
    ]
