# Generated by Django 5.0.6 on 2024-07-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_contract_type_smart_rapido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='type_smart_fibre',
            field=models.CharField(blank=True, choices=[('20M', '20M'), ('50M', '50M'), ('100M', '100M')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type_abonnement',
            field=models.CharField(choices=[('ADSL', 'ADSL'), ('VDSL', 'VDSL'), ('SMART FIBRE ', ' SMART FIBRE '), ('SMART RAPIDO', 'SMART RAPIDO')], max_length=100),
        ),
    ]
