# Generated by Django 5.0.6 on 2024-07-15 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_contract_type_smart_fibre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='type_abonnement',
            field=models.CharField(choices=[('ADSL', 'ADSL'), ('VDSL', 'VDSL'), ('SMART FIBRE', 'SMART FIBRE'), ('SMART RAPIDO', 'SMART RAPIDO')], max_length=100),
        ),
    ]
