# Generated by Django 5.0.6 on 2024-07-15 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_alter_contract_type_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='type_smart_adsl',
            field=models.CharField(blank=True, choices=[('SMART ADSL 10M', 'SMART ADSL 10M'), ('SMART ADSL 12M', 'SMART ADSL 12M'), ('SMART ADSL 20M', 'SMART ADSL 20M')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='type_abonnement',
            field=models.CharField(choices=[('SMART ADSL', 'SMART ADSL'), ('VDSL', 'VDSL'), ('SMART FIBRE', 'SMART FIBRE'), ('SMART RAPIDO', 'SMART RAPIDO')], max_length=100),
        ),
    ]
