# Generated by Django 5.0.6 on 2024-07-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0010_contract_type_smart_adsl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delegation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='gouvernorat',
            name='name',
        ),
        migrations.RemoveField(
            model_name='localite',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='localite',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='localite',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='localite',
            name='name',
        ),
        migrations.AddField(
            model_name='delegation',
            name='codeDelegation',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='delegation',
            name='nomDelegation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gouvernorat',
            name='codeGouvernorat',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='gouvernorat',
            name='nomGouvernorat',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='localite',
            name='codeLocalite',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='localite',
            name='nomLocalite',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
