# Generated by Django 5.0.7 on 2024-07-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_remove_delegation_name_remove_gouvernorat_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodePostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gouvernorat', models.CharField(max_length=100)),
                ('delegation', models.CharField(max_length=100)),
                ('localite', models.CharField(max_length=100)),
                ('code_postal', models.CharField(max_length=10)),
            ],
        ),
    ]
