# Generated by Django 5.0.7 on 2024-07-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0013_remove_codepostal_code_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='coordonnees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
