# Generated by Django 5.0.7 on 2024-08-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_contract_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
